### ISSUE TITLE
Unable to sign in - Error code 801

### ISSUE THREAD

**Issue by kbakk** [microsoft/vscode-pull-request-github#1221]
- Extension version: 0.8.0
- VSCode Version: 1.35.0
- OS: MacOS 10.14.5
- Browser: Firefox 67.0.1

Steps to Reproduce:

1. Add extension to VS Code, click prompt to sign in
2. Approve app in GitHub.com
3. On page [https://vscode-auth.github.com/authorize?...](https://vscode-auth.github.com/authorize?authServer=https://github.com/&callbackUri=vscode://GitHub.vscode-pull-request-github/did-authenticate&scope=read:user%20user:email%20repo%20write:discussion), select Continue

Expected:

Extension is authenticated

Actual:

_Message in browser is shown:_

```
Oh no! An error occurred!

Please restart the sign in process from the editor.

Error code 801

```

Is not logged in in VS Code. 

Have tried:

- restarting the sign in process
- using private window in Firefox
- removing Github for VS Code from https://github.com/settings/applications

Neither work, is not able to log in.

**Comment by smarnach** [comment]
Same issue for me on Ubuntu 19.04, Firefox 68.0.2, vscode 1.37.1, extension version 0.10.0.

The only workaround I found was to make Chrome my default browser temporarily, so apparently the login workflow is broken in Firefox.

**Comment by AFZ31** [comment]
Same thing for me on Ubuntu 18.04.3 LTS, Firefox 69.0, vscode 1.37.1, extension 0.10.0

**Comment by LarnuUK** [comment]
Having this problem  as well on Ubuntu 19.04. I either get "Error code 801" or the address wasn't understood by Firefox. Disappointing that this issue has been ignored for 3 months, as seems that using GitHub from VSCode is therefore impossible.

**Comment by LarnuUK** [comment]
I got around this, however, by clicking the Sign in button, and then going to the bottom where it where "Signing into GitHub", where VSCode then asks you for a token. Go to https://github.com/settings/tokens and create a new token and paste that into then screen box. Then type `Github.com` in the next box. You are then connected.

**Comment by SilWorkBench** [comment]
I faced the same issue on Win10 with Edge and found the following workaround:
Restart the sing in procedure from vs code. When Edge is opened, do not continue the procedure on Edge. Instead, copy the URL that from Edge to Internet Explorer and continue the process in internet explorer. That worked for me.

**Comment by LarnuUK** [comment]
> I faced the same issue on Win10 with Edge and found the following workaround:
> Restart the sing in procedure from vs code. When Edge is opened, do not continue the procedure on Edge. Instead, copy the URL that from Edge to Internet Explorer and continue the process in internet explorer. That worked for me.

Edge and Internet Explorer don't work on Mac or Ubuntu though. It's a Windows only Browser. :)

**Comment by SilWorkBench** [comment]
> Edge and Internet Explorer don't work on Mac or Ubuntu though. It's a Windows only Browser. :) The problem appears to extend from the functionality not working on other OSes.

Of course you are right. Just thinking that the issue may be related to the browser and not to vscode. My 2 cents...

**Comment by Ayivugwe** [comment]
Hi there. I was facing the same problem and now I'm signed in.

Steps : 

1) Click Sign in to github.com
2) Edge( in my case) opens the athaurization  link 
3) Copy the link
4) In my case, I pasted it in Firefox Developer Edition and hint Enter
5) Success message : Authorization was successful
6) Then I was redirected to VS Code.
7) That's all and now I'm signed in.

**Comment by ericblade** [comment]
Same problem here on a new laptop that I'm configuring.  No matter what browser I used, if it was the default browser, it wouldn't work.  Started with Edge, tried Chrome, Vivaldi.  Ended up pasting the URL into Vivaldi and that got it to work.

**Comment by gorandp** [comment]
I got that problem but I fixed it.
OS: Ubuntu 18.04.3
Browser: Firefox 72.0.1
VS Code version: 1.41.1
Extension version: 0.14.0

Try this:
1. Log out from "github.com" in your default browser if you are already
2. Go to VS Code and try to sign in with the extension.
3. Press continue and then try to log in
4. Success page

But after that I got an error message inside the VS Code extension. And I get stuck there for a while.
Tried it again applying same procedure (because if not, I get the error page).
Uninstall, Install, Disable, Enable the extension. Same error inside VS Code.
I gave up.

When I was writing this comment I wanted to share my error message from inside de code editor, so I enabled the extension (and without restarting the code editor) I applied the procedure of above, got the success page and clicked on open in the pop-up box. It then logged in. Don't know why.

Hope it is helpful.

**Comment by wolftales** [comment]
> I got around this, however, by clicking the Sign in button, and then going to the bottom where it where "Signing into GitHub", where VSCode then asks you for a token. Go to https://github.com/settings/tokens and create a new token and paste that into then screen box. Then type `Github.com` in the next box. You are then connected.

I am experiencing this same issue with Ubuntu 20.04 Dev, Mozilla, and VS Code.  I kept getting a popup asking me to let Mozilla know it crashed.

Following LarnuUK worked for me. 

1. Download extension
2. get popup - clear it
3. Create token @ Github
4. Click "Signing into github.com message for the extension"
5. inputing the token
Add: 6. Typing in "github.com" (It doesn't default)
Add: 7. Ignoring the login error message the plugin says.

It appears to work after that.

Only thing I'd add is:

**Comment by Nixs108** [comment]
> I got around this, however, by clicking the Sign in button, and then going to the bottom where it where "Signing into GitHub", where VSCode then asks you for a token. Go to https://github.com/settings/tokens and create a new token and paste that into then screen box. Then type Github.com in the next box. You are then connected.

Worked for me. Thanks a bunch!

**Comment by owpm** [comment]
Is this going to be fixed anytime soon? Concerning that you need to workaround a forced oauth signin.

**Comment by kas** [comment]
Ubuntu 20.04 LTS, Firefox 76.0.1, Visual Studio Code 1.45.1

I can't explain what exactly fixed this for me, but after trying the process three times, it finally worked. When I'd get the error web page, I'd completely close out of Visual Studio Code each time and try the process again. I was trying to access a private GitHub repository.

**Comment by Ryuno-Ki** [comment]
Visual Studio Code 1.45.1
Firefox 75.0
Chromium 81.0.4044.138 
Sabayon Linux

Same here. Custom Protocol was not detected. Chromium asked for opening with xdg-open.

The format looks like
`vscode://vscode.github-authentication/did-authenticate?windowId=1&code=<hexcode>&state=<uuid>` (had to make Chromium my default browser because Firefox failed)

Using Personal Access Token failed with invalid format in VS Code.

**Comment by Xmetalfanx** [comment]
seeing the same thing here .... currently on Arch Linux .. vscode 1.45.1 ... Firefox 77.0.1 ... not sure this has anything to do with it but i cleared temp internet data including cookies too and it doesn't seem to help ... at least not yet

**Comment by Ryuno-Ki** [comment]
From the format, my first point of investigation would be, whether the `vscode:` protocol was correctly registered in Firefox.

**Comment by erikmonroy** [comment]
Visual Studio Code: 1.45.1
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 (chrome os linux)

I too have tried a Personal Access Token, as well as a chrome settings reset. Neither have worked, nor has copying the access token provided when the authorization fails in the browser.

**Comment by Caleb-Irwin** [comment]
Interestingly I also got the same error in brave (a chromium based browser), but when I disabled the default ad blocker and ublock origin it worked.

**Comment by xxpedro** [comment]
> 
> 
> Hi there. I was facing the same problem and now I'm signed in.
> 
> Steps :
> 
>     1. Click Sign in to github.com
> 
>     2. Edge( in my case) opens the athaurization  link
> 
>     3. Copy the link
> 
>     4. In my case, I pasted it in Firefox Developer Edition and hint Enter
> 
>     5. Success message : Authorization was successful
> 
>     6. Then I was redirected to VS Code.
> 
>     7. That's all and now I'm signed in.

Thaaaankkk Youu

**Comment by zaxhutchinson** [comment]
VSCodium: 1.47
Firefox: 78.0.1
Xubuntu: 20.04

Fresh OS install. Experience is similar to the above trying to push to a private repo. Popup says I need to sign-in with Github. When I click the affirmative button, Firefox opens asking to authorize. Clicking the green button produces the "oops, something went wrong".

I tried the solution above that says to close everything out several times. That worked. But then when I close codium and try again, the pop-up returns. However, I noticed that if click Cancel on the popup or hit the "x" to close it, an entry text box opens at the top of codium asking for my git username and then a second asking for the password. That works. But this is clunky.

**Comment by viniciusov** [comment]
In VS Code -> Settings, search for Github.
You will find the following option:
```
Github: Git Authentication

- [x] Controls whether to enable automatic GitHub authentication for git commands within VS Code.

```

**Uncheck** this box to enter the Github credentials on VS Code everytime you need (instead of using your browser).

**Comment by zaxhutchinson** [comment]
> In VS Code -> Settings, search for Github.
> You will find the following option:
> 
> ```
> Github: Git Authentication
> 
> - [x] Controls whether to enable automatic GitHub authentication for git commands within VS Code.
> ```
> 
> **Uncheck** this box to enter the Github credentials on VS Code everytime you need (instead of using your browser).

Perfect! Thanks.

**Comment by makeable** [comment]
Seems like its broken in Edge Legacy. I guess even microsoft dont use Edge!

**Comment by r-pankevicius** [comment]
@makeable Same issue with Edge Legacy. Workaround: Let default browser to open github page. Copy URL, open Chrome, paste URL there and go. That worked for me, no need to change default browser.

**Comment by ghtmtt** [comment]
I also have the same problem. The default browser is Firefox but even if I copy/paste the link into Chrome I always get a broken link:

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-17T10:49:51.211Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.0-1-amd64

**Comment by makeable** [comment]
Is there a project we can contribute to for this auth endpoint? Its clearly broken, and would like to fix it!

**Comment by GoToSeattle** [comment]
Step 1
In VS Code -> Settings, search for Github.
You will find the following option (**Uncheck this box**):
Github: Git Authentication
- [x] Controls whether to enable automatic GitHub authentication for git commands within VS Code.
Uncheck this box to enter the Github credentials on VS Code everytime you need (instead of using your browser).

Step 2
Go to [https://github.com/settings/applications](https://github.com/settings/applications)
and then click tab "**Authorized OAuth Apps**", then click 
![QQ图片20200803061605](https://user-images.githubusercontent.com/13615953/89133834-fe13d000-d551-11ea-99fc-702bdf61733d.png)
![QQ图片20200803062154](https://user-images.githubusercontent.com/13615953/89133836-ffdd9380-d551-11ea-8432-6802d20e2ce9.png)
![QQ图片20200803062256](https://user-images.githubusercontent.com/13615953/89133837-00762a00-d552-11ea-9b4b-ff91421712b7.png)
![QQ图片20200803062341](https://user-images.githubusercontent.com/13615953/89133852-2b607e00-d552-11ea-9e8f-4e9f1abe8c81.png)

**Comment by jeffswt** [comment]
Confirmed on Windows 10 1909 18363.959, Firefox 79.0.

**Comment by nvmnghia** [comment]
macOS 10.14.6, latest VSCode, cannot use Chrome 85 to sync. Copy paste the link to Safari works though.

**Comment by pavel-francirek** [comment]
Confirmed, no need to set other browser (other than Firefox) default. Just copy Github confirmation page's URL to Safari and continue without error (tested with latest Firefox, Safari, VScode, macOS).

**Comment by DiegoRosas12** [comment]
I had no problems pasting the token in vscode but it only worked when I pasted my personal access token generated in GitHub.com not the one that your browser windows tells you to copy.

**Comment by dav3ku** [comment]
Lamentablemente tengo el mismo problema pero en Codespaces de GitHub.

**Comment by oryws** [comment]
Was having the same issue on OSX 10.15.6, no matter the browser.
I finally got it to work by pulling both vscode and firefox dev edition from full screen mode into the same desktop then it simply worked

**Comment by Helloshomax** [comment]
> 
> 
> > In VS Code -> Settings, search for Github.
> > You will find the following option:
> > ```
> > Github: Git Authentication
> > 
> > - [x] Controls whether to enable automatic GitHub authentication for git commands within VS Code.
> > ```
> > 
> > 
> > **Uncheck** this box to enter the Github credentials on VS Code everytime you need (instead of using your browser).
> 
> Perfect! Thanks.

Thank you very much, worked. Windows 7 SP1. VS code Exploration.

**Comment by oxdead** [comment]
same problem on CentOS 8, Mozilla Firefox

**Comment by obitstack** [comment]
I have experienced the same problem @
Arch Manjaro 20.2
Ubuntu 19.10
Ubuntu 20.04
Kernel version 5.8
VScode 1.51.1

It seems that if I try to authenticate via the integrated GIT extension, URL socket in VScode is not active during token transfer. 
What worked for me: 
1: Choose copy adress @ the vscode prompt 
2: restart VScode, paste adress in firefox  
then it opens the VScode URL connection and you're done.

**Comment by ggabriel96** [comment]
Just happened to me on a fresh Linux install.
Reading the comments here, I tried simply removing `GitHub for VSCode` from my `Authorized OAuth Apps` and then signing in again. It worked :man_shrugging: 
Maybe the case where it is already authorized is not being handled correctly?

**Comment by cmolina** [comment]
I finally got it working.

1. Opened any vscode extension in your default browser, for example [change-case](https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case)
2. Click "Install" button. The browser will  show an alert asking how do you want to handle `vscode` links. Select the Visual Studio Code app
3. You now should see the extension page open in vscode

Now your browser should be able to complete the sign-in process: repeat the failed workflow and follow any alerts that instruct your browser to open vscode after the login.

Tested with macOS Big Sur, Firefox Developer Edition 85.

**Comment by BexDunn** [comment]
I have this issue working on a CentOS HPC machine that I don't have admin rights to, where I can't update firefox or use Chrome. So far none of the above solutions/workarounds have worked for me.

**Comment by dotnetspec** [comment]
git integration etc. issues with VSCode:
I have fixed this:
Upgrade Linux Mint from 18.3 to 20.0
Uninstall flatpack version of VSCode (I had to use that version with 18.3)
Install official VSCode Linux version from:
https://code.visualstudio.com/
Now no git integration issues.

**Comment by AR-Student824** [comment]
Happening on Windows 10 Pro Insider w/ latest vsc

**Comment by udondan** [comment]
Thanks  @cmolina, confirming this worked for me. Same scenario, Big Sur, Firefox. This was bugging my for months!

**Comment by andrewufrank** [comment]
the error still occurs on bullseye in feb 2021. impossible to fix? 
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.0-3-amd64

**Comment by pkruk2** [comment]
Happened to me. Maybe related to multiple opened VSCode editors (with different workspaces)? I started sign-in in vscode 1, but after web browser asked to me open vscode, it opened vscode 2 (or I selected wrong one), and it signed in correct. I noticed it was the wrong one, signed out, tried signing in again from the first vscode, but now it didn't work (the error 801)

**Comment by arkadyt** [comment]
**Managed to get around the issue in my browser by just reloading the page right after it shows that 801 error.**

**Comment by soredake** [comment]
## Solution for firefox:
1. Set "system handler" for vscode protocol:
![Screenshot_20210304_095732](https://user-images.githubusercontent.com/5204968/109931074-0c38f300-7cd1-11eb-9f72-29c253ea26b4.png)
2. Yay it redirects to vscode now!
![Screenshot_20210304_095747](https://user-images.githubusercontent.com/5204968/109931089-10fda700-7cd1-11eb-84a2-43849468bfb5.png)

**Comment by Abdelfatahh** [comment]
I had the same issue on ubuntu with firefox. 
The steps I did to solve this issue was the following -> 
1- you go to the bottom left and click on the sync on button. 
2- you sign in with github and it will open with your default browser (in my case was chrome) 
3- you'll copy the link and open a new incognito tab (private window in firefox).
4- you'll login and it will success!

**Comment by stuzenz** [comment]
> Same issue for me on Ubuntu 19.04, Firefox 68.0.2, vscode 1.37.1, extension version 0.10.0.
> 
> The only workaround I found was to make Chrome my default browser temporarily, so apparently the login workflow is broken in Firefox.

Workaround was good for me on archlinux. Thanks!

**Comment by jcemerson** [comment]
I just had this issue with Firefox on Linux Mint. It was resolved by just turning off Enhanced Tracking Protection in Firefox on the page where the error is presented. At that point, the page reloaded and authorization completed, after which I turned Enhanced Tracking Protection back on.

![image](https://user-images.githubusercontent.com/41130857/113145887-869c5a80-921e-11eb-87e3-04dd6ccd30e2.png)

![image](https://user-images.githubusercontent.com/41130857/113146645-720c9200-921f-11eb-88e5-d54141ca29a0.png)

From what I can tell, all (or most at least) of the mentioned issues reported involve Firefox and the workarounds often consist of using a different browser for the authorization.

This isn't a case of Firefox being broken. It's just that Firefox (with Enhanced Tracking Protection on) is more restrictive of what websites can do (e.g. set cookies, run tracking scripts, capture canvas details) and some sites, for better or worse, require these things in order to function. In these cases, you just need to create (temporary or permanent) exceptions to the Protection rules.

To me, this isn't a bug at all, just a conflict of functionalities.

**Comment by ramen-mukherjee** [comment]
VSCode got updated to v1.55.0, immediately started getting this error intermittently. If I am not getting this error, I am getting "Sign in failed: FetchError: request to https://vscode-auth.github.com/token?code=<<TOKEN>> failed, reason: certificate signature failure".

**Comment by Coronon** [comment]
I am also using Firefox. What worked for me was to copy the link immediatly after the site opened in the normal browser and paste it into a private Firefox session to then login. Multiple authentications need fresh private sessions (For me its was 1x Settings Sync, 1x Codespaces).

**Comment by djose1164** [comment]
My solution was: Go to https://github.com/settings/tokens and then revoke all.

**Comment by mathiasmag** [comment]
In my case this was due to a VPN. With it disconnected it just worked. I was authenticated already so no knew login was required after disconnecting the VPN. So the login with VPN worked but it was some action after login that failed and gave me 801.

**Comment by emosGambler** [comment]
> Hi there. I was facing the same problem and now I'm signed in.
> 
> Steps :
> 
>     1. Click Sign in to github.com
> 
>     2. Edge( in my case) opens the athaurization  link
> 
>     3. Copy the link
> 
>     4. In my case, I pasted it in Firefox Developer Edition and hint Enter
> 
>     5. Success message : Authorization was successful
> 
>     6. Then I was redirected to VS Code.
> 
>     7. That's all and now I'm signed in.

In my case this helped. I did:
1) `git push -u origin main`
2) VSC asked to login to github.com, I've clicked the button
3) On default it opened for me on Firefox, I've copied the URL and pasted it to Chromium (Ubuntu)
4) I was redirected to github login page and then all was easy

Regards.

**Comment by mannympardo** [comment]
> I faced the same issue on Win10 with Edge and found the following workaround:
> Restart the sing in procedure from vs code. When Edge is opened, do not continue the procedure on Edge. Instead, copy the URL that from Edge to Internet Explorer and continue the process in internet explorer. That worked for me.

Conversely I had the issue on Firefox and Mac OS and used Safari instead.

**Comment by vuon9** [comment]
I got this problem on Firefox 89.0.2 (64-bit), macOS 11.2.2

**Comment by necessityOVO** [comment]
> In my case this was due to a VPN. With it disconnected it just worked. I was authenticated already so no knew login was required after disconnecting the VPN. So the login with VPN worked but it was some action after login that failed and gave me 801.

I get same error when using a VPN, but can't connect to github in chrome after disconnecting it, I don't know what to do

**Comment by TrafalgarWaterDLaw** [comment]
I find that the best thing to do is to just restart the whole process because for me it is always happening and I have to redo the whole process again, it is really tedious but it is the only solution I have got.

**Comment by build3r** [comment]
This happened to me when I was using github in a different container than deafult on Firefox. Opening the link in right container fixed the problem.

**Comment by shahrier-nafis** [comment]
sign up first

**Comment by cybertcode** [comment]
**aquí está la solución gente al final** 
https://www.mclibre.org/consultar/informatica/lecciones/vsc-git-repositorio.html

**Comment by cybertcode** [comment]
> **aquí está la solución gente al final **
> https://www.mclibre.org/consultar/informatica/lecciones/vsc-git-repositorio.html

**Comment by peano1608** [comment]
The easy way is log out from github (if already log in)
Then open authorization from VS Code, and log in again
Maybe it need to authorization again
It works successfully on my Firefox

**Comment by baraBlz** [comment]
I think I have me the right choice, the Truth is the only Right way.

Domagoj ***@***.***>    Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by TomaszWaszczyk** [comment]
You can solve this by copying and pasting token manually into VSCode:

![image](https://user-images.githubusercontent.com/1605705/128994334-416c653c-b8b2-4da5-b6d6-006aae192561.png)

**Comment by samuela** [comment]
> You can solve this by copying and pasting token manually into VSCode:
> 
> ![image](https://user-images.githubusercontent.com/1605705/128994334-416c653c-b8b2-4da5-b6d6-006aae192561.png)

Error code 801 is presented before reaching the "success" screen offering the auth token.

**Comment by liamdawson** [comment]
Oddly enough, I got to the error 801 page, opened developer tools, refreshed the page to see whether anything would come up in the console, and it worked. Next sign-in 801'd again, and once again worked when I refreshed the page _with devtools open_.

**Comment by g-hayashi** [comment]
I wish if it helps someone else.
I got same 801 error In my environment and we have forward proxy.
I added the vscode-auth.github.com to its ssl decode exception list then it works normally.

**Comment by TylerLeonhardt** [comment]
It's been a week and I've heard nothing... gonna close this for now but please let me know if you still see it.

**Comment by TylerLeonhardt** [comment]
verification:

* Go through the auth flow for GitHub a few times on a few different platforms

You shouldn't see an 801 error.

**Comment by r-pankevicius** [comment]
@TylerLeonhardt Closed this issue for the 5th time!
 - opened on Jun 7, 2019 · 77 comments, after 2.5 years.
 Can it be true?

**Comment by alexr00** [comment]
I tried signing in on Windows and Ubuntu alternatingly (3x on each). No error.

**Comment by TylerLeonhardt** [comment]
The service that use to display the Error code 801 has been gone for almost a month now. The log in flow is completely different now in 1.66 (and is even better in 1.67 coming this week). Can you please open an issue in microsoft/vscode with details?

**Comment by Chrimle** [comment]
> The service that use to display the Error code 801 has been gone for almost a month now. The log in flow is completely different now in 1.66 (and is even better in 1.67 coming this week). Can you please open an issue in microsoft/vscode with details?

Hi, I don't know if I want to replicate the issue, as I seem to have overcome it. Just wanted to comment that this (or a similar login issue) is still present and how it could be solved. :+1:

**Comment by omonimus1** [comment]
Same issue here, 23/06/22 
I download & Reinstall VSC code the given source and it keep failing. 

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/23085146/175308685-81bdf503-d2a1-421c-9e77-a7d8da9a42d9.png">

**Comment by Shadowblitz16** [comment]
please reopen this and actually fix it.
![image](https://user-images.githubusercontent.com/2453707/207975837-94480409-9bef-45c0-90cd-2391252b3b2a.png)

**Comment by addohm** [comment]
> This is still an issue. The "copy link to another browser" did the trick for me.

Elaborate?  How are you getting a link at all?

**Comment by Shadowblitz16** [comment]
> [@Shadowblitz16](https://github.com/Shadowblitz16) for that error, the Troubleshooting Guild will help. You likely don't have an application on your machine that handles secrets, like gnome-keyring.

I stopped using vscode as soon as rider became free.
It wasn't due to me not having a secret handling app it's because you guys hardcoded it to gnome keyring and i'm on kde

**Comment by TylerLeonhardt** [comment]
@Shadowblitz16 We don't hardcode to gnome-keyring. We follow what Chromium does. There is detection logic of what your UI system is and then we use that respective UI system's keyring. Sometimes Chromium gets it wrong... which is why the troubleshooting guide shows how to override to another keyring.
