### ISSUE TITLE
Its possible connect to github enterprise

### ISSUE THREAD

**Issue by vaclavbenes** [microsoft/vscode-pull-request-github#1793]
Hi, its possible configure extension with different github. (Use of github enterprise)

**Comment by GABeech** [comment]
It looks like they removed support for GHE with version 0.16. 

It took me a bit of digging, and it doesn't look like there was any notification that this support was going away - but I don't pay close attention to the issues here. 

I'm personally a bit confused about the reasoning (that they don't have resources to test against it). Especially since they appear to be using Octokit.rest which has first class support for GHE out of the box.

**Comment by drayfar** [comment]
+1 I can no longer use this extension now that #1616 is in

**Comment by deerawan** [comment]
I experienced this issue in `0.16`. As interim, we could install the previous version `0.15.0` in VS Code

![image](https://user-images.githubusercontent.com/1243921/81761833-55377500-950e-11ea-88d0-5151f2f2c04e.png)

**Comment by dvsoukup** [comment]
I read the change log on this.  I can sympathize with the lack of hands to assist with development on the enterprise functionality.

That being said though, it's a no-go to do that.  A "solution" is not to just use a previous version (v0.15).  Many thousands of people whom use this extension are now effectively blocked from ever getting updates.  You rip the rug out from underneath them.

A nicer scenario would have been to say "hey, we can't continue to develop on enterprise connectivity.  But we'll leave in what we have in there now".  Let the versions continue to advance, but don't rip this out from folks.

You leave lots of folks scratching their heads, wasting hours trying to figure out why their tooling isn't working.  Only to eventually come here, and see this mysterious decision to pull the plug on GHE support.

I love this extension, 5-stars for sure.  But the decision to do this is of 1-star quality.

**Comment by azinoviev** [comment]
> I love this extension, 5-stars for sure. But the decision to do this is of 1-star quality.

+1

I'm really upset about this decision. GitHub Enterprise integration was extremely useful feature.
If there's not enough resources to test it, it'd prefer to have it buggy, than not to have it at all.

**Comment by Richard-Lynch** [comment]
+1, very unhappy to see this feature go, would love to know if there’s any effort which can be made by the community to get it back

**Comment by alexanderkjeldaas** [comment]
@Richard-Lynch fork?

**Comment by JunhwanPark** [comment]
I'm waiting for Github Enterprise support..............

**Comment by khepin** [comment]
Locked out as well. Don't have the JS chops to contribute the required code sadly.

**Comment by danecreekphotography** [comment]
This is tough. I used this constantly and now it is gone. Sure I can stay with the old version, but then I miss out on all the improvements that are sure to happen over time.

**Comment by Richard-Lynch** [comment]
I’m happy to contribute back a fix/enhancement if a maintainer can give some guidance here on what would be acceptable? 

Either extending the **GitHub authentication provider** extension to support enterprise, or creating a new **GitHub Enterprise authentication provider** extension to do same?

@RMacfarlane could you give any guidance? Is there an issue tracking this or is this something that isn't coming back for some reason?

**Comment by Richard-Lynch** [comment]
For anyone who is following this ticket, it was mentioned in #1850 that this is being looked at by internal contributors to asses the viability of bringing back enterprise support, so we’ll hopefully know more soon. 

The official workaround right now is to downgrade to 0.15.0 [wiki](https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported)

Very much appreciated, thanks for the awesome project 😁

Comment in question https://github.com/microsoft/vscode-pull-request-github/issues/1850#issuecomment-642844191

**Comment by jnials** [comment]
Yeah, this is a non-starter for me.  Left a review to that effect since that may get the attention of someone outside the developement team.

**Comment by jeduan** [comment]
I'm inconvenienced by this since I can only use an old version now, but actually support this decision. 

I imagine GHE is a minuscule amount of users, and reducing scope will be the best path forward to keep this extension maintained. Everyone who's inconvenienced by this should use their energy convincing their companies who are likely spending tens of thousands of dollars in GHE, to contribute to this extension and VSCode's authentication features. We can't expect a couple of contributors to do all the work without burning out.

**Comment by ProLoser** [comment]
I think a problem is the recent vscode architecture change around authentication providers has left an obscure path forward for someone looking to re-add support for enterprise.

Perhaps someone could do some research/exploration around solutions on how to get this done with the new auth.

**Comment by dvsoukup** [comment]
> A downgrade was recommended as a workaround, but this version finally stopped working with the latest version of VSCode.
> Can't you do something about it?
> Sorry this comment is a machine translation.

It did?  v15.0 seems to still connect to GHE just fine for me, even with the most recent VS Code update.

**Comment by danecreekphotography** [comment]
Any update on this? Is there any plan to put this on a roadmap for resolution?

**Comment by jasonwilliams** [comment]
pings @RMacfarlane

**Comment by pcj** [comment]
This is just a drive-by comment since I am looking at this right now.  

With https://github.com/microsoft/vscode-pull-request-github/commit/9f7d6a09447a611131591f1253b48c4eb6f79000#diff-a46298735cf7c583b6e833c09a3653e1R192, the implementation is dramatically simpler and relies on the builtin extension github-authentication.  Here's what I think would need to occur to restore GHE support:

1. Make the AUTH_RELAY_SERVER configurable: currently this is hardcoded to be `vscode-auth.github.com` (Example: https://vscode-auth.github.com/authorize?authServer=https://github.com/&callbackUri=vscode://GitHub.vscode-pull-request-github/did-authenticate&scope=read:user%20user:email%20repo%20write:discussion). 
 AUTH_RELAY_SERVER is at https://github.com/microsoft/vscode/blob/1961260ef3f6993b9c57f7dadccb00f423a1c1b2/extensions/github-authentication/src/githubServer.ts#L16.  This AFAIK is closed source.  It needs to be open-sourced so that GHE customers can stand one up, or new code added to the github-authentication extension that facilitates GHE support via personal access tokens somehow (probably the preferred option).
2. Make the graphql client configurable.  Currently this is hardcoded to api.github.com.  https://github.com/microsoft/vscode-pull-request-github/blob/f821fc0180415d96541c08f4e15868899a79be7a/src/github/credentials.ts#L177-L184

Again, that's just a driveby look at the problem.  Hopefully @RMacfarlane can shed more light on the blocking issues.

**Comment by enigma0Z** [comment]
Just to add to this discussion, even if it was provided as "best effort" support for GHE, that'd be preferable to just removing the feature entirely, if possible.

Based on what is said in the wiki (where the suggestion to downgrade to 0.15.x is made), is it possible to add a secondary "workaround" authentication mode that does what the 0.15 version did? Effectively requesting the GitHub (GHE) domain & a token which a user could generate and paste in to VSCode...

**Comment by ggcatu** [comment]
Seems that with the latest VSCode updates, 1.5 is no longer an option https://github.com/microsoft/vscode-pull-request-github/issues/2206 as we just get empty content

**Comment by docwhat** [comment]
Since the plugin doesn't support GitHub Enterprise (GHE) and 0.15 no longer works, should someone purge all the GHE instructions from the wiki?

**Comment by Cetlan** [comment]
This is a pity. I was just going through a PR review from a coworker and thinking it would be really nice to be able to see his comments all inline in my code while I'm working on addressing them. Then I thought "Hey, somebody probably already thought that, let me see if there's an extension." Found this... and then found that like seemingly everything else in VS Code, it doesn't support GHE even if it did at one time." The lack of GitHub Enterprise support in VS Code GitHub plugins is really disappointing. I guess I should at least be glad that I didn't find this a few months ago to appreciate it, only to have it torn away.

Downgrading to 0.15 doesn't work for me either, so I assume it's fully broken at this point as suggested by a couple earlier posters? (no commands work, the panel is empty, I see no way to actually use it)

**Comment by jkt628** [comment]
at least 99% of my work is against GHE.  the fact it works with public github is merely "interesting" whereas the fact it is broken with GHE is a major blocker.

**Comment by WafflesMcDuff** [comment]
> at least 99% of my work is against GHE. the fact it works with public github is merely "interesting" whereas the fact it is broken with GHE is a major blocker.

For anyone who might have missed it earlier in this long-running issue, there is a workaround while the devs sort this out:
![image](https://user-images.githubusercontent.com/24410823/107388818-37f6fd80-6ac4-11eb-8e18-de4fc0b9afa1.png)

1. Find the extension in extension marketplace.
2. Right click on it and choose Install another version...
3. Choose 0.15.0
4. When it's done installing, click the reload required button.
5. Voila.

**Comment by cfiderer** [comment]
@WafflesMcDuff Version 0.15.0 doesn't work anymore with VS Code 1.53.0.

**Comment by kabel** [comment]
If you're willing to do some "beta" testing, I'd love to get some feedback on my PRs that add support back. You'll have make some adjustments to your config and shortcut to launch `code`.

1. Change your shortcut to `code.exe` or `code - insiders.exe` to include the options ` --enable-proposed-api vscode.github-authentication`
2. Install the matching vsix builds from my branches (rename zip to vsix)
   - code 1.53+: [github-authentication-0.0.2a1.zip](https://github.com/microsoft/vscode-pull-request-github/files/5972747/github-authentication-0.0.2a1.zip)
   - code-insiders 1.54 2021-02-12+: [github-authentication-0.0.2a2.zip](https://github.com/microsoft/vscode-pull-request-github/files/5972753/github-authentication-0.0.2a2.zip)

3. Install the test integration vsix from my branches (rename zip to vsix)
   - [vscode-pull-request-github-0.23.1.zip](https://github.com/microsoft/vscode-pull-request-github/files/5972755/vscode-pull-request-github-0.23.1.zip)

4. Set `settings.json` values for
   - `"github-enterprise.uri": "https://domain-of-ghe.your-enterprise.tld"`
   - `"githubPullRequests.authenticationProvider": "github-enterprise"`

**Comment by selcukduman** [comment]
@kabel, I can confirm the extension works with our github enterprise server. I created several queries, closed/reopened the application several times and can successfully see all of the issues/PRs related to my searches. Also, I can still see the github.com project related info for my projects there.

I don't see the icon for the extension though. It just appears blank. My platform is Windows10 with native vscode installation.

**Comment by kabel** [comment]
> I don't see the icon for the extension though. It just appears blank.

Bad packaging on my part that included some mainline fixes not production ready.

**Comment by ProLoser** [comment]
@kabel you have just earned my sponsorship (and a tip for @selcukduman too)

**Comment by selcukduman** [comment]
The icon is back and the extension works fine. I tested on the latest stable version (1.53.2).
Thanks @kabel. I appreciate the fix.

**Comment by lupalby** [comment]
@kabel amazing work! I truly hope your solution will be merged soon

**Comment by lupalby** [comment]
@kabel Just tested on my computer too and it works beautifully. Also working in WSL remote development. Great work

**Comment by segraef** [comment]
@kabel let me know if you need any further support or testing on my GHE. Hopefully this gets merged soon.

**Comment by bavarianbidi** [comment]
@kabel can also confirm, that it works under linux as well. Great Job :+1: 

but it's not possible to make suggestions (not sure what's the root-cause for this missing feature is)

**Comment by jasonwilliams** [comment]
@bavarianbidi i don’t think that feature exists in general so it’s not related to this issue. I think there’s a separate issue for that.

**Comment by jasonwilliams** [comment]
@kabel, I can also confirm that after following the instructions from https://github.com/microsoft/vscode-pull-request-github/issues/1793#issuecomment-778269272 the extension works with our GitHub Enterprise Server 2.20.14. I can see pull requests in the drop down and do all the things i could before.

**Comment by jnials** [comment]
Looking forward to seeing this merged.  I'm on linux and hoping it works there as well.

**Comment by Talor-A** [comment]
<img width="465" alt="Screen Shot 2021-02-16 at 9 28 47 AM" src="https://user-images.githubusercontent.com/11509865/108099392-65e6bf80-7039-11eb-9925-6ffd32b51f20.png">
I see this error trying to view PR descriptions. 

details:

github authentication ext: 0.0.2a1
pull request extension: 0.23.1a2
GHE Server version:  2.19.3

happy to provide any more info.

**Comment by vortechs2000** [comment]
This is working for me on Mac and VSCode `Version: 1.53.2`

So awesome!

**Comment by kabel** [comment]
> I see this error trying to view PR descriptions.
> 
> details:
> 
> github authentication ext: 0.0.2a1
> pull request extension: 0.23.1a2
> GHE Server version: 2.19.3

@Talor-A 
GHE Server 2.19 is well passed end-of-life. This is from GHE product doc for **2.20:**
![image](https://user-images.githubusercontent.com/675956/108101419-cf23fe00-704c-11eb-8dea-82f48dd937fb.png)

This was probably one of the reasons support was dropped for enterprise all together. The version fragmentation is too much to keep track of. Don't expect upstream authors to keep supporting product versions that have been discontinued.

**Comment by Talor-A** [comment]
@kabel thanks, guess I'll have to bug our GHE admins about updating 😅

**Comment by chromey** [comment]
And here's another happy successful beta test. Thanks a lot @kabel, this is very much appreciated. 🚀 
macOS 11.2.1
VS Code: 1.53.2
GHE: 2.22

**Comment by selcukduman** [comment]
@kabel When I create the issue, it's adding a blob url pointing to github.com as the domain instead of our github enterprise server in the issue body text. I can update it before creating the issue in the issue edit panel, so not a big problem, but just wanted to let you know.

**Comment by kabel** [comment]
> When I create the issue, it's adding a blob url pointing to github.com as the domain

Yes, there are likely a few implementation details that aren't fully ironed out to work with GHE. Examples that need to be reviewed and reported.

* https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L216
* https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L264
* https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L292
* https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L481

**Comment by peterpk** [comment]
Mac VSCode 1.53.2 .  I did all of the above, starting VSCode from Terminal with `code --enable-proposed-api vscode.github-authentication` .  When I first tried to log in, after tweaking the settings, it prompted me for a Personal Access Token and then, apparently, did nothing.  The explorer view did not update, no error message or confirmation message.  I tried clicking on "Login" again and didn't even get a prompt.

So being in IT, I closed Code and re-opened it.  And without having to do anything else, the Issues and PR views were there and populated.

So it is working, but seemingly "something" happened the first time around that wasn't exactly right.  I don't know if there are logs or anything that I might be able to send along, or if it's "good enough" since it seems to be working now.

**Comment by peterpk** [comment]
As a note for anyone trying @kabel 's beta-test ... MS just dropped v0.24 of the official extension and it overwrote the VSIX.  I uninstalled and then re-installed from VSIX and it's working again.

**Comment by ProLoser** [comment]
Perhaps we should add a link and updates to the wiki to point to this discussion so that more votes / eyes will see and support getting this wrapped up and merged.

**Comment by peterpk** [comment]
@kabel I grabbed 0.24.1-a1 and installed it, but now VSCode is telling me that `githubPullRequests.authenticationProvider` is an Unknown Configuration Setting.  Is that intentional? Do the "beta" instructions at https://github.com/microsoft/vscode-pull-request-github/issues/1793#issuecomment-778269272 need updating?

**Comment by kabel** [comment]
> Do the "beta" instructions at [#1793 (comment)](https://github.com/microsoft/vscode-pull-request-github/issues/1793#issuecomment-778269272) need updating?

Sure. Since 388a937d9a4c290b628f812985f743e0726ea030, Both providers can be used at the same time. No need for a configured switch.

**Comment by peterpk** [comment]
OK, cool.  I had to add the GHE server and token to `githubPullRequests.hosts` but now it seems to be working again. :)

Also, it seems the `--enable-proposed-api vscode.github-authentication` switch is no longer required?

**Comment by catskul** [comment]
Any word on when the changes in https://github.com/microsoft/vscode-pull-request-github/commit/388a937d9a4c290b628f812985f743e0726ea030 and the like will make it into a release?

**Comment by Ygilany** [comment]
@RMacfarlane any plans to merge this soon?

**Comment by jasonwilliams** [comment]
Thanks for reviewing and merging @RMacfarlane 
Will https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported need to be updated?

**Comment by connor4312** [comment]
@jasonwilliams are you able to verify whether this works for you?

**Comment by jasonwilliams** [comment]
> @jasonwilliams are you able to verify whether this works for you?

I was waiting for v1.57 to be released to test it, as I’m assuming that’s when I’ll be able to try it out?

**Comment by rzhao271** [comment]
@jasonwilliams you should be able to test the changes using VS Code Insiders. You may need to use the following extension: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders.

**Comment by jasonwilliams** [comment]
@connor4312 @rzhao271 

* Installed VSCode Insiders
* Installed pull request github nightly
* I set my enterprise URI, filling out "github-enterprise.uri" (I included the schema)
* Then needed to restart VSCode
* Then i signed in following the instructions here:
https://github.com/microsoft/vscode/pull/115940#issuecomment-838838680

It does work thanks (I needed to reload a few times but got there).

**Comment by alexr00** [comment]
I'm going to mark this issue as verified since we have [several](https://github.com/microsoft/vscode/pull/115940#issuecomment-840751668) [users](https://github.com/microsoft/vscode/pull/115940#issuecomment-839241313) [who](https://github.com/microsoft/vscode/pull/115940#issuecomment-838949494) commented about their success in the PR comment thread.

@jasonwilliams I'd love to provide you with some suggestion about what might be going wrong, but I'm entirely reliant on the community for enterprise support and test.

**Comment by jasonwilliams** [comment]
@alexr00 understandable, although now Microsoft is a [parent to Github](https://news.microsoft.com/announcement/microsoft-acquires-github/) I'm surprised you cannot attain an enterprise instance for testing.

**Comment by ElanHasson** [comment]
Hi @kabel,

Thanks for fixing the GHE stuff, I can finally see pull request activity!

> When I create the issue, it's adding a blob url pointing to github.com as the domain
> * https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L216
> * https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L264
> * https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L292
> * https://github.com/microsoft/vscode-pull-request-github/blob/217cc2201935f6d29e6065f79ff1dca27fc7424b/src/issues/util.ts#L481


Do you (or anyone else) have any info on when these will be updated to use the `baseUrl` from GHE settings? 
![image](https://user-images.githubusercontent.com/234704/148082373-a6289d24-a18d-40d4-8899-40b0da2c2c8c.png)

**Comment by Sunchock** [comment]
Hello there, I would like to share with you my adventures using this plugin.

First, I've installed **VSCode Insiders** and **GitHub Pull Request and Issues** plugin. But when I wanted to install **GitHub Pull Request and Issues Nightly Build** too as mentionned before : a message in the market-place page tell us of **Nightly Build** is included in **GitHub Pull Request and Issues** previsionnal version. (So may I have already get it ?) I've set the uri in the settings with my corporate ghe instance base url.
Then when i want to log me. It stills redirect me to github.com and i don't know why.

So when i was to the webpage to log me on github.com. I took the original url and replace the last argument **authServer** (who it was 'https://github.com' again ..) by the same argument I put in the uri setting and .. it works !
Finaly i can connect using my GHE instance account but it was only the first step

In the second part, I had to generate a new token in my GHE account settings and use this token in VSCode Insiders regardless the token given in the webpage after the login.

And that's it ! (Finally !)

**Comment by alexr00** [comment]
@cpatti97100 a new version of VS Code stable was released last week (version 1.64) and I released a new version of GitHub Pull Requests and Issues (version 0.36.0) last week too so you're probably good to go.

**Comment by wrslatz** [comment]
Does login for GitHub Enterprise work _without_ also logging into GitHub.com? I can't seem to get this to work with the latest versions. I'm happy to open a separate issue to troubleshoot further.

**Comment by cpatti97100** [comment]
Hey @alexr00 thank you for reaching out!

So at the moment I have Code Version: 1.64.1 (Universal) and GitHub Pull Requests and Issues 0.36.0

in settings I have
```
"github-enterprise.uri": "https://github.*****.com",
```

when I start the app and go the extension page, I see this

![image](https://user-images.githubusercontent.com/2529599/153266388-b48d08de-af6b-467e-9153-bbc3f30a0e18.png)

then I do the sign in flow into my private regular github account

![image](https://user-images.githubusercontent.com/2529599/153266888-dbbb81df-5ba2-42a6-bf1a-d2473126b328.png)

and I end up in this state

![image](https://user-images.githubusercontent.com/2529599/153266797-41e1217f-4f22-43c7-8fd3-a49f755f3f76.png)

then I click on sign in with github enterprise and it asks me for a token, but no web page with it ever opened

![image](https://user-images.githubusercontent.com/2529599/153267194-29075297-0fe1-4b1b-b3b4-c7a2a9aba47f.png)

where should I get it?

Thank you!

**Comment by wrslatz** [comment]
I was able to generate an access token in the GitHub Enterprise instance (under Developer Settings for your user).

The login to GHES seems to work in my case (from the GitHub Authentication logs), but the extension still can't recognize or pull the projects for my workspaces (I see logs saying the repo isn't recognized and can't find the remotes).

**Comment by cpatti97100** [comment]
> I was able to generate an access token in the GitHub Enterprise instance (under Developer Settings for your user).
> 
> The login to GHES seems to work in my case (from the GitHub Authentication logs), but the extension still can't recognize or pull the projects for my workspaces (I see logs saying the repo isn't recognized and can't find the remotes).

success! thanks!

**Comment by luyu12** [comment]
Hi, 
I have installed VS Code version 1.66.2 (Universal), MAC version 12.3.1, GitHub PR and Issues version 0.40.0. But when I clicked the 'sign in' button in the welcome panel, it showed the message below (not sign in using GitHub Enterprise..)
![Screen Shot 2022-04-15 at 2 09 29 PM](https://user-images.githubusercontent.com/31711748/163632192-e3005e26-f9f6-452f-9f01-76d9eec9356f.png).
In settings, I have: 
Github-enterprise: Uri : https://***.githubprivate.com.

How can I make this work for me? Thanks!
