### ISSUE TITLE
big pull request not loading

### ISSUE THREAD

**Issue by RobertGalatNordic** [microsoft/vscode-pull-request-github#2741]
Issue Type: <b>Bug</b>

I have a big pull request (>100 files changed) and when I click on `>` under Waiting For My Review,  to see the changes, it keeps loading, and nothing happens. I can checkout the PR, but I can not see the files changed, nor start a review. 

Extension version: 0.26.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.8.0-53-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 4199)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 3, 2|
|Memory (System)|15.46GB (1.36GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 8f4baa7d-87f6-456d-9200-7180f882bc82|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30301612
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by RMacfarlane** [comment]
Is the pull request by chance in a public repo? If you could link to it that would help us try to reproduce this. Otherwise, could you open the Output Panel in VSCode and change the dropdown to "GitHub Pull Request" and copy the log from there?

**Comment by KrisDavie** [comment]
Also having this issue, similarly a big PR (specifically: https://github.com/aertslab/SCope/pull/381)

Extension version: 0.26.0
VS Code Version: 1.56.2
OS version: Win 10 Version 20H2 (19042.985) (Connecting to a WSL remote session)
<details>
<summary> WSL Info: </summary>

```
➜ uname -a
Linux MOIRAE 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

➜ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
</details>

<details>
  <summary>Details:</summary>

```
  VS Code Version: 1.56.2 (user setup)
  Commit: 054a9295330880ed74ceaedda236253b4f39a335
  Date: 2021-05-12T17:13:13.157Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Windows_NT x64 10.0.19042
```
</details>

Here is the contents of the "GitHub Pull Request" output panel:
```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found.
[Info] Found GitHub remote
[Info] Review> current branch cleanup/373-frontend-stage3 is associated with pull request #381
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data

```

**Comment by RobertGalatNordic** [comment]
> Is the pull request by chance in a public repo? If you could link to it that would help us try to reproduce this. Otherwise, could you open the Output Panel in VSCode and change the dropdown to "GitHub Pull Request" and copy the log from there?

Unfortunately the PR is in private repo :( The output panel is very similar to what @KrisDavie provided. I run the test again with output in debug mode. Here is a result (I changed organization, repository and project name for placeholders) 

https://gist.github.com/RobertGalatNordic/9950865f265f1d47f2f37abb649098d4

It is running the requests, and getting those responses constantly, and it looks like infinite loop. 
I hope I could help

**Comment by KrisDavie** [comment]
From my end, it seems like after a long time (not sure _exactly_ how long), the `Commits` have finally populated, but the `Files` have not.

![image](https://user-images.githubusercontent.com/5079892/119115031-ff51b300-ba26-11eb-9a44-8f5351302eb9.png)

New output:

```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found.
[Info] Found GitHub remote
[Info] Review> current branch cleanup/373-frontend-stage3 is associated with pull request #381
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> Error: GraphQL error: API rate limit exceeded for user ID 5079892.
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: API rate limit exceeded for user ID 5079892.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found.
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch pixi-to-three
[Info] Review> no matching pull request metadata found on GitHub for current branch pixi-to-three
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: API rate limit exceeded for user ID 5079892.
[Info] Review> This PR is no longer valid
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: API rate limit exceeded for user ID 5079892.
[Info] Review> This PR is no longer valid
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: API rate limit exceeded for user ID 5079892.
[Info] Review> This PR is no longer valid

```

**Comment by akosyakov** [comment]
Downgrading to 0.25.1 fixes it, for PRs with many files something draining API rate limit and also makes everything super slow too load. I found there were introduced getPullRequestFileViewState request which delays loading of the PR node. Probably it is a cause.

**Comment by adedayojs** [comment]
I have the same issue here. I'm using the lates version (i installed it today)

**Comment by egor-xyz** [comment]
I have the same issue, after rollback to version 0.25.1 - all works

**Comment by fedeci** [comment]
I'm having the same issue for some big [Babel](https://github.com/babel/babel) PRs.

**Comment by joeshub** [comment]
Same issue here, in the output it seems to get stuck on  this line
```
[Info] Review> Resolving pull request 
[Info] Review> Fetching pull request data
....
```

**Comment by akosyakov** [comment]
@alexr00 It is a regression since 0.26 Could you please consider fixing it as well for next milestone 🙏 There even seems to be a PR: https://github.com/microsoft/vscode-pull-request-github/pull/2766

It is quite bad, because opening a single big PR makes the whole extension unusable for sometime. It cannot do GitHub api calls anymore.

**Comment by alexr00** [comment]
Will take a look!

**Comment by alexr00** [comment]
Anyone have a large PR open that for testing this with?

**Comment by travisbell** [comment]
Yup, same issue for me. I have a private PR here (sorry, nothing public to share) with ~330 changed files and this extension just doesn't work with the current version. I downgraded to 0.25.1 like the guys above and everything works once more. Hopefully you guys can get this fixed with the latest version.

Thanks!

**Comment by rzhao271** [comment]
Yep, I tested using the PR https://github.com/microsoft/vscode/pull/128085.
If you want, you can switch to [VS Code Insiders](https://code.visualstudio.com/insiders/) and get the [PR nightly extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders).

**Comment by Danl2620** [comment]
I installed the nightly extension version `v2021.7.10959` on VS Code version detailed below and the bug still exists. Unfortunately it's a PR in a private repo. Here some info on it:

Commits: 250
Files changed: 3663


My VS code version:
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.3.0
```

**Comment by alexr00** [comment]
I tested with https://github.com/microsoft/vscode/pull/128085 (which is slow but works), but your PR has an order of magnitude more files in it.

**Comment by ryan-efendy** [comment]
Still getting `API rate limit exceeded` on the nightly extension version  `2021.8.13506` on VSCode Insiders version `1.60.0-insider`. I'm trying to open a small PR in a private repo.

System info:
```
macOs Big Sur Version 11.5.1
Apple M1 Chip
```

**Comment by sguillia** [comment]
This issue still persists even with reasonably small PRs

Commits: 10
Files changed: 149
Open-source: no
Last message in output channel: `Review> Fetching pull request data`

| Version       	| Behavior of this extension's panel 	|
|---------------	|------------------------------------	|
| 0.24.0        	| Changed files appear instantly     	|
| 0.25.0        	| Changed files appear instantly     	|
| 0.25.1        	| Changed files appear instantly     	|
| 0.26.0        	| Loads forever                      	|
| v2021.8.13506 nightly	| Loads forever                      	|

**Comment by pakrym** [comment]
https://github.dev/Azure/azure-sdk-for-net/pull/25181/files/780fb817caff1355834d93816fe3ec337b238019..616287c8b676a98fb47ee81eaa388c2fed2ecdf8 

Takes very long to load on VSCode insiders and a nightly build of PR extension.

**Comment by heaths** [comment]
Though I've been able to use the extension in the past to open larger PRs using github.dev, it wasn't working this afternoon. The PR "tab" would show up as focused initially, but after a second or two would disappear and the file "tab" would be selected. The only warning or error I could find of any possible relevance was:

```
[2021-11-29 16:13:52.656] [window] [warning] Ignoring the error while validating workspace folder vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a223235343932227d7d/Azure/azure-sdk-for-net - No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a223235343932227d7d/Azure/azure-sdk-for-net'
```

Repro video:

https://user-images.githubusercontent.com/1532486/143967617-bb0c1581-3481-46a1-b274-e68cf49b60bd.mp4

This was against the insiders VSCode on github.dev. I tried the latest extension on stable as well prior to this with the same behavior.

**Comment by ves-fyayc** [comment]
Still getting API rate limit exceeded on extension version v0.35.2022012009 on VSCode. I'm trying to open a small PR in a private repo.

**Comment by alexr00** [comment]
@ves-fyayc are any of the PRs you're opening public and if so can you share a link? If now, can you share the output from "GitHub Pull Request"?

**Comment by ves-fyayc** [comment]
> 

The PRs are private and the output in the console when I try to load a PR is 
`[Info] GithubRepository> Unable to fetch issues without milestone: Error: GraphQL error: API rate limit exceeded for user ID 51325222.
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: API rate limit exceeded for user ID 51325222.`

**Comment by alexr00** [comment]
@ves-fyayc can you try signing out and signing in again in VS Code with your GitHub account? The Accounts menu is near the bottom of the activity bar.

You shouldn't be getting any rate limiting if you're signed, so it's possible something is up with your sign in. If signing out and in again solves it, then I can have the extension automatically prompt you do so when the rate limit error occurs.

**Comment by ves-fyayc** [comment]
> @ves-fyayc can you try signing out and signing in again in VS Code with your GitHub account? The Accounts menu is near the bottom of the activity bar.
> 
> You shouldn't be getting that rate limiting if you're signed in, so it's possible something is up with your sign in. If signing out and in again solves it, then I can have the extension automatically prompt you do so when the rate limit error occurs.

I tried sign out and in againt and it worked, so it is probably a good idea to do the automatical prompt when the rate limit occurs.

**Comment by alexr00** [comment]
Thanks for confirming that @ves-fyayc. I will make the change: https://github.com/microsoft/vscode-pull-request-github/issues/3282

**Comment by alexr00** [comment]
@RobertGalatNordic the fix for https://github.com/microsoft/vscode-pull-request-github/issues/3605 should have this useable for you scenarios (the PR I was testing with had almost 900 changed files). The issue was that we were running some expensive git operations on every file in the PR, even though the operations' results weren't needed until the file was actually opened.

Note that this change is available in the 0.45.* prerelease build of the extension. It will be in the next stable version.

Between the above change and https://github.com/microsoft/vscode-pull-request-github/issues/3187, you should have only a slight delay for a PR with hundreds of changed files.

@Danl2620 if you still have a PR with thousands of files to test with I would be very interested to hear if your experience has improved with the latest pre-release build. 

Closing this issue as I expect https://github.com/microsoft/vscode-pull-request-github/issues/3605 resolves it, but performance will be a continued area of focus, so if you seen any slowness please do file another issue.

**Comment by dharmveerjakhar** [comment]
I was facing the same issue and it was my adblocker which created the issue in the first place, working fine now.
