### ISSUE TITLE
503 on vscode-auth.github.com when signing in to GitHub Enterprise

### ISSUE THREAD

**Issue by romanlevin** [Microsoft/vscode-pull-request-github#662]
- Extension version: 0.2.3
- VSCode Version: 1.27.2
- OS: macOS 10.14.1 

Steps to Reproduce:

1. Open Code with a GitHub Enterprise repo open
2. Click "sign in" on the extension pop-up
3. Click green "Continue" button
4. Wait for a while (60s?)
5. See a Heroku 503 page (see below)

<img width="490" alt="image" src="https://user-images.githubusercontent.com/132421/48005088-d7bdc800-e112-11e8-82bd-88738b777036.png">

**Comment by romanlevin** [comment]
I think it's a similar issue to https://github.com/Microsoft/vscode-pull-request-github/issues/591

**Comment by vinod386** [comment]
I ran into the same issue. I tried to give a PAT as well, but the extension says invalid token.

**Comment by rockypabillore** [comment]
> 
> 
> I ran into the same issue. I tried to give a PAT as well, but the extension says invalid token.

I'm having the same issue. After I approve my account, it automatically takes me to 404 page. I click on the "signing in to github.(corp).com..." it asks for token. what token?

**Comment by YeThor** [comment]
same here, I tried a personal access token but it didn't work. just keep saying it's an invalid token, keep showing the error page

**Comment by queerviolet** [comment]
@YeThor @rockypabillore That sounds like an issue fixed in the most recent release. What version of the extension are you using? If you update the extension, does it help?

**Comment by testerez** [comment]
I just tried with the last version and got the same issue.

**Comment by csholmq** [comment]
> 0.3.0
>
> Breaking Changes
>
> From 0.3.0, you at least need VSCode 1.30 (including Insiders) to install and run the extension.

**Comment by vinod386** [comment]
I've just tried this with VSCode 1.30 - The OAuth flow still failed with the same old application error as in the picture from above comments, but giving a PAT and server name allowed me to sign in.

**Comment by romanlevin** [comment]
@vinod386 how do you manually provide a token?

**Comment by vinod386** [comment]
@romanlevin  You could just click on the signing in.. field on the bottom left of VSCode, then provide the token and server at the top.

**Comment by ProLoser** [comment]
@vinod386 where did you get the token and what scope / permissions did you set?

**Comment by vinod386** [comment]
@ProLoser You can follow this to create your token - https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

The scope I had on my token is - read:user, repo, user:email, write:discussion
