### ISSUE TITLE
deleting branch after squashing PR not working anymore since vscode 1.98.0

### ISSUE THREAD

**Issue by jorenham** [microsoft/vscode-pull-request-github#6699]
After squashing a PR in [numpy/numtype](https://github.com/numpy/numtype) via the web interface, then refreshing in VSCode, I press the "delete branch" button, and see the following logs:

```
2025-03-07 14:54:29.773 [error] [GitHubRepository+0] Unable to compare commits between numpy:main and numpy:faster-pyright: HttpError: Not Found
```

This is happening since I upgraded VSCode to 1.98.0. I tried both the release- and pre-release versions of the extension.

- Extension version: 0.107.2025030604
- VSCode Version: 1.98.0
- OS: Ubuntu 22.04 (PopOS)
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Squash (or merge) a PR in [numpy/numtype](https://github.com/numpy/numtype) in the browser
2. refresh the PR in VSCode
3. attempt to delete the branch in VSCode

**Comment by alexr00** [comment]
@jorenham Do you still see this? I squash then delete on a regular basis and haven't seen this issue.

**Comment by jorenham** [comment]
> [@jorenham](https://github.com/jorenham?rgh-link-date=2025-03-20T16%3A46%3A49.000Z) Do you still see this? I squash then delete on a regular basis and haven't seen this issue.

I believe it does, but to be sure, I'll try it right now with https://github.com/numpy/numtype/pull/345.

**Comment by jorenham** [comment]
after squashing through the github web interface:

![Image](https://github.com/user-attachments/assets/a7c15542-61ff-4030-97cc-5517f36e7b9b)

after squashing, and hitting "refresh" in vscode:

![Image](https://github.com/user-attachments/assets/bb3fda46-b37b-45ed-85d3-0fbea1f70f3e)

so I pressed "Delete branch...":

![Image](https://github.com/user-attachments/assets/f5e066f7-be5c-41a9-b783-884aaa3bbfc1)

I clicked on "Ok", but the branch still exists locally and is still checked out:

![Image](https://github.com/user-attachments/assets/d88cfe30-7954-4d87-8989-1243c480936a)

**Comment by alexr00** [comment]
Organization repo. Like this repo or `microsoft/vscode`.

**Comment by alexr00** [comment]
@jorenham, next time you see this, can you share the output from "Git"?

**Comment by jorenham** [comment]
and again with https://github.com/python/typeshed/pull/13777, while paying more attention to limit the logs to what's relevant:

```
2025-04-07 16:07:28.832 [info] > git config --local -l [1ms]
2025-04-07 16:07:30.235 [info] > git branch -D ctypes._._type_ [1ms]
2025-04-07 16:07:30.235 [info] error: Cannot delete branch 'ctypes._._type_' checked out at '/home/joren/Workspace/typeshed'
2025-04-07 16:07:30.248 [info] > git config --get commit.template [1ms]
2025-04-07 16:07:30.262 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/ctypes._._type_ refs/remotes/ctypes._._type_ [1ms]
2025-04-07 16:07:30.287 [info] > git status -z -uall --ignore-submodules [13ms]
2025-04-07 16:07:30.287 [info] > git for-each-ref --sort -committerdate --format %(refname)%00%(objectname)%00%(*objectname) [1ms]
```

**Comment by jorenham** [comment]
```
❯ git status
On branch ctypes._._type_
Your branch is based on 'origin/ctypes._._type_', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean
```

**Comment by alexr00** [comment]
I think I see what's going on, thanks!

**Comment by TylerLeonhardt** [comment]
@jorenham can you verify this is fixed in [VS Code Insiders](https://code.visualstudio.com/insiders} and the Pre-release version of the GitHub Pull Request extension?

**Comment by jorenham** [comment]
> [@jorenham](https://github.com/jorenham) can you verify this is fixed in [VS Code Insiders](https://code.visualstudio.com/insiders) and the Pre-release version of the GitHub Pull Request extension?

Working on it; but CI seems to be having trouble getting out of bed today
https://github.com/numpy/numtype/pull/536

**Comment by TylerLeonhardt** [comment]
> but CI seems to be having trouble getting out of bed today

relatable

**Comment by jorenham** [comment]
With VSCode insiders and the pre-release extension, it seems to work now. But with the stable VSCode and the pre-release ext, it's still the same problem

**Comment by TylerLeonhardt** [comment]
Yes that's because the latest version of the pre-release ext is not compatible with the current Stable version of VS Code. When the next Stable VS Code is released (next week), there will also be a GH PR extension release which will work there. Thanks for verifying!

**Comment by jorenham** [comment]
Thanks for fixing this!
